name: nyc_stage3_clickhouse

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8.14.39
    container_name: nyc_clickhouse
    restart: "no"
    ports:
      - "8123:8123"
      - "9009:9000"
    environment:
      CLICKHOUSE_DB: nyc_taxi
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - ../data/clickhouse:/var/lib/clickhouse
      - ../clickhouse/init:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      nyc-data-net:
        aliases:
          - clickhouse  # RFC-совместимый алиас без подчёркивания для JDBC/Java URI

networks:
  nyc-data-net:
    name: nyc_data_net
    external: true
